version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: zinko-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3000
      - SUPABASE_URL=https://hyfqsjidyxufsatveaih.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5ZnFzamlkeXh1ZnNhdHZlYWloIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODg1MTI2OCwiZXhwIjoyMDk0NDI3MjY4fQ.GddsczShASoZtHM4ofEtAeXR4FzRKGYJum0RvQXHb2A
      - CLERK_PUBLISHABLE_KEY=pk_test_Y29udGVudC1wYW5kYS02My5jbGVyay5hY2NvdW50cy5kZXYk
      - CLERK_SECRET_KEY=sk_test_IZCKj9g5sLGcTR5ycXtkSTdxDHMLRfgkEpIR0WwGJZ
      - CLERK_WEBHOOK_SECRET=whsec_hYmlvBb7oVPFHPN5YrgkgV+n7slXICtm
      - GROQ_API_KEY=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
    volumes:
      - ./backend:/app/backend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/backend/node_modules
    networks:
      - zinko-network

  frontend:
    build:
      context: .
      dockerfile: next-frontend/Dockerfile
    container_name: zinko-next-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_Y29udGVudC1wYW5kYS02My5jbGVyay5hY2NvdW50cy5kZXYk
      - CLERK_SECRET_KEY=sk_test_IZCKj9g5sLGcTR5ycXtkSTdxDHMLRfgkEpIR0WwGJZ
      - NEXT_PUBLIC_SUPABASE_URL=https://hyfqsjidyxufsatveaih.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5ZnFzamlkeXh1ZnNhdHZlYWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4NTEyNjgsImV4cCI6MjA5NDQyNzI2OH0.FKmLk0OQmK2lqJXh1P5pX6Y8Z9L0M1N2O3P4Q5R6S7T
    volumes:
      - ./next-frontend:/app/next-frontend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/next-frontend/node_modules
    networks:
      - zinko-network

networks:
  zinko-network:
    driver: bridge
